config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :messages, only: [:index, :show, :new, :create, :destroy]
  resources :chatrooms, only: [:index, :show]
  resources :users, only: [:index]

  put '/add_friend', to: 'users#add_friend', as: :add_friend
  get '/profile/:id', to: 'users#show_profile', as: :profile
  put '/accept_friend', to: 'users#accept_friend', as: :accept
  put '/reject_friend', to: 'users#reject_friend', as: :reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :friend1, class_name: "User"
  belongs_to :friend2, class_name: "User"
  validates :friend2_id, :friend1_id, presence: true

  def recipient(user)
    self.friend2 == user ? friend1.username : friend2.username
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  has_one_attached :photo
  reverse_geocoded_by :longitude, :latitude
  validates :longitude, :latitude, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :messages
  has_many :chatrooms_as_friend1, source: :chatrooms, foreign_key: :friend1_id
  has_many :chatrooms_as_friend2, source: :chatrooms, foreign_key: :friend2_id
  has_friendship
  validates :username, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
require "open-uri"
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :ip_print
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :photo)}
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def ip_print
    if Rails.env.production?
      @ip = current_user.current_sign_in_ip if current_user
      puts "Ip Address: #{@ip}"
    else
      @ip = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
      puts "Ip Address: #{@ip}"
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = policy_scope(Chatroom.where(friend1: current_user).or(Chatroom.where(friend2: current_user))).order(created_at: :desc)
  end

  def show
    @message = Message.new
    @chatroom = Chatroom.find(params[:id])
    # raise
    # raise
    authorize @chatroom
  end
end

app/controllers/messages_controller.rb
require 'open-uri'

class MessagesController < ApplicationController
  def index
  end

  def show
    @message = Message.find(params[:id])
    authorize @message
    map_marker
  end

  def new
    @message = Message.new
    authorize @message
    get_user_coordinates_from_ip
    map_marker
  end

  def create
    @friend2 = User.find(params[:friend2])
    @message = Message.new(message_params)
    @message.user = current_user
    get_user_coordinates_from_ip
    @chatroom = Chatroom.find(params[:id]) if params[:id]
    @address = Geocoder.search([@message.latitude, @message.longitude])
    authorize @message
    if @chatroom || @chatroom = Chatroom.where(friend1: current_user, friend2: @friend2).first || @chatroom = Chatroom.where(friend2: current_user, friend1: @friend2).first
      @message.chatroom = @chatroom
    else
      @chatroom = Chatroom.new
      @chatroom.friend1 = current_user
      @chatroom.friend2 = User.find(params[:friend2])
      @chatroom.save!
      @message.chatroom = @chatroom
    end
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to chatroom_path(@chatroom)
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    authorize @message
    @message.destroy
    redirect_to messages_path
  end

  private

  def get_user_coordinates_from_ip
    user_location = JSON.parse(URI.open("http://iplocate.io/api/lookup/#{@ip}").read)
    @message.latitude = user_location['latitude']
    @message.longitude = user_location['longitude']
  end

  def map_marker
    @markers = [{
      lat: @message.latitude,
      lng: @message.longitude
      }]
  end

  def message_params
    params.require(:message).permit(:content, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @home = true
    # redirect_to chatrooms_path if current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = policy_scope(User)
    @users = @users.select {|user|
      !current_user.friends.include?(user) && user != current_user
    }
  end

  def add_friend
    @user = User.find(params[:user_id])
    authorize @user
    current_user.friend_request(@user)
    redirect_to users_path
  end

  def show_profile
    @user = User.find(params[:id])
    authorize @user
  end

  def accept_friend
    @user = User.find(params[:user_id])
    authorize @user
    current_user.accept_request(@user)
    redirect_to users_path
  end

  def reject_friend
    @user = User.find(params[:user_id])
    authorize @user
    current_user.decline_request(@user)
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def format_friend_list(user)
    user.friends.map do |friend|
      [friend.username, friend.id]
    end
  end

end

app/views/chatrooms/index.html.erb
<div class="background">
  <div class="header header-index d-flex">
    <div class="img-icon-separate">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-sm" %>
      <% else %>
        <img class="avatar-sm" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="">
      <% end %>
      <i class="fas fa-search white icon-search"></i>
    </div>
    <h4 style="color: white;" class="my-3 caps-title">My Spots</h4>
  </div>
  <div class="chat-container chat-background pt-2">
    <ul class="list-unstyled">
      <% @chatrooms.each do |chatroom| %>
      <li class="chat-card">
        <%= link_to chatroom_path(chatroom), class:"link-unstyled" do %>
          <div class="d-flex p-3 centered">
            <% if current_user == chatroom.friend1 && chatroom.friend2.photo.attached? %>
              <%= cl_image_tag chatroom.friend2.photo.key, class: "avatar-sm" %>
            <% elsif current_user == chatroom.friend2 && chatroom.friend1.photo.attached? %>
              <%= cl_image_tag chatroom.friend1.photo.key, class: "avatar-sm" %>
            <% else %>
                <img class="avatar-sm" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="">
            <% end %>
            <div class="user-details ml-3">
            <%  if current_user == chatroom.friend1  %>
              <p class="bold-text" style="color: lightgoldenrodyellow"><%= chatroom.friend2.username %></p>
            <% else %>
              <p class="bold-text" style="color: lightgoldenrodyellow"><%= chatroom.friend1.username %></p>
            <% end %>

            <%  if current_user == chatroom.friend1  %>
            <%# raise %>
              <% last_message = chatroom.friend2.messages.last %>
                <% if last_message.class == Message && !last_message.read %>
                  <p style="font-weight: bold; color: lightgoldenrodyellow">You have a new spot</p>
                <% elsif !last_message.nil? %>
                  <p class=" opacity-text" style="color: lightgoldenrodyellow"><%= chatroom.friend2.messages.last.content %></p>
                  <% else %>
                  <p class=" opacity-text" style="color: lightgoldenrodyellow">Spot sent</p>
                <% end %>
            <% else %>
              <% last_message = chatroom.friend1.messages.last %>
                <% if last_message.class == Message && !last_message.read %>
                  <p style="font-weight: bold; color: lightgoldenrodyellow">You have a new spot</p>
                <% elsif !last_message.nil? %>
                  <p class=" opacity-text" style="color: lightgoldenrodyellow"><%= chatroom.friend1.messages.last.content %></p>
                  <% else %>
                  <p class=" opacity-text" style="color: lightgoldenrodyellow">Spot sent</p>
                <% end %>
            <% end %>

          </div>
        </div>
      </li>
    <!-- <div class="underline"></div> -->
      <% end %>


      <% end %>

    </ul>
  </div>
  <%= render 'shared/new_message_button' %>
</div>

<!-- https://images.unsplash.com/photo-1606290979721-07c4dd5431a9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9' -->

app/views/chatrooms/show.html.erb
<div class="background">
  <div class="text-container">
    <div class="header d-flex">
      <% if current_user == @chatroom.friend1 && @chatroom.friend2.photo.attached? %>
        <%= cl_image_tag @chatroom.friend2.photo.key, class: "avatar-medium ml-3 mt-3 mb-3" %>
      <% elsif current_user == @chatroom.friend2 && @chatroom.friend1.photo.attached? %>
        <%= cl_image_tag @chatroom.friend1.photo.key, class: "avatar-medium ml-3 mt-3 mb-3" %>
      <% else %>
          <img class="avatar-medium ml-3 mt-3 mb-3" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="">
      <% end %>
      <!-- <img class="avatar-medium ml-3 mt-3 mb-3" src="https://images.unsplash.com/photo-1606248174040-df0429d73afa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80" alt=""> -->
     <h4 class="ml-4 mt-3 mb-2 caps-title" style="color: white;"><%=@chatroom.recipient(current_user)%></h4>
    </div>
    <div class="text-body chat-container" data-chatroom-id="<%= @chatroom.id %>">


        <% @chatroom.messages.each do |message| %>
          <%= render 'messages/message', message: message %>
        <% end %>



    </div>
    <div class="new-message">

      <%= simple_form_for(@message, html: { class: "message-new"}) do |f| %>
        <div class="image-upload">
          <label for="file-input">
            <i class="fas fa-paperclip icon-fas"></i>
          </label>
          <%= f.file_field :photo, id: "file-input" %>
        </div>

        <%= f.input :content, label: false, wrapper_html: { class: 'text-area-input' } ,input_html: { class: 'text-input' } %>
        <%= hidden_field_tag :friend2, @chatroom.friend2 == current_user ? @chatroom.friend1.id : @chatroom.friend2.id %>
        <%= hidden_field_tag :chatroom_id, @chatroom.id %>
        <%#= f.hidden_field :longitude%>
        <%#= f.hidden_field :latitude%>
        <%#= f.submit "send" label %>
        <%#= f.button :submit do %>
       <%= button_tag type: 'submit', class: "submit-none" do %>
           <i class="fas fa-paper-plane icon-fas" aria-hidden="true"></i>
       <% end %>
          <!-- <i class="fas fa-paper-plane icon-fas" id="btn"></i> -->
        <%# end %>
      <!--   <div class="submit">
          <label for="submit-btn">
            <i class="fas fa-paper-plane icon-fas" id="btn"></i>
          </label>


        </div> -->
      <% end %>

    </div>
    </div>
    <%= render 'shared/new_message_button' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ourspot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <% if current_page?(chatrooms_path) %>
      <%= render 'shared/new_message_button' %>
    <% end %>
  </body>

</html>

app/views/messages/_message.html.erb
<% if !message.read %>
  <% message_service = UserInMessageRadius.new(current_user, @ip, message) %>
  <% can_view = message_service.perform %>
<% end %>
<% if message.user == current_user %>
  <% justify = "end" %>
  <% send = "send" %>
<% else %>
  <% justify = "start" %>
  <% send = "receive" %>
<% end %>

<% if can_view || message.user == current_user || message.read%>
  <% if message.photo.attached? %>
    <div class="justify-content-<%=justify%> link-msg">
      <%= link_to message_path(message) do %>
        <div class="card mb-4 card-img-<%=send%>" style="width: 14rem;">
          <%= cl_image_tag message.photo.key, class:"card-img-top img-#{send}"%>
          <div class="card-body">
            <p class="card-text"><%= message.content %></p>
          </div>
          <span class="name-position-<%=send%>"><%= message.user.username %></span>
        </div>
      <% end %>
      </div>
  <% else %>
    <div class="justify-content-<%=justify%> mb-4">
      <div class="msg-content-<%=send%>">
        <span class="black"><%= message.content %></span>
        <span class="name-position-<%=send%>"><%= message.user.username %></span>
      </div>
    </div>
  <% end  %>
<% else %>
  <div class="justify-content-start mb-4">
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Go here to view your message.</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div id="map"
                style="width: 100%; height: 600px;"
                data-markers="<%= [{ lat: message.latitude, lng: message.longitude}].to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
          </div>
        </div>
      </div>
    </div>
    <div class="msg-content-receive">

      <span class="black" data-toggle="modal" data-target="#exampleModal">You have a new spot. Tap here to find out where to go.</span>

      <span class="name-position-receive"><%= message.user.username %></span>
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="background">
  <div class="header header-index d-flex">
    <h4 style="color: white;" class="mt-3 caps-title">Add this spot</h4>
  </div>
  <div class="container-form">
    <div class="form-container">
      <%= simple_form_for @message, innerHTML: { class: "d-flex"}  do |f| %>

          <%= simple_fields_for @chatroom do |form| %>
            <%= form.label 'Choose a friend:', required: false %>
            <%= form.select :friend2, options_for_select(format_friend_list(current_user)) %>
          <% end %>
          <%= f.input :content, wrapper_html: { class: 'text-area-icon' },  label: 'Write a message:' %>

            <!-- <div class="image-upload-icon mt-2 mb-2">
            <label for="file-input">
              <i class="fas fa-plus icon-fas rnd-fas"></i>
            </label> -->

          <%= f.input :photo, :as => :file, label: 'Add a photo (if you\'d like):', class: 'mt-2' %>
          <div class="d-flex">
            <%#= link_to "Cancel", root_path, class: "btn btn-main btn-success rounded-pill w-100 mr-4"  %>
            <%= f.submit "Create", class: "btn btn-main-dark rounded-pill w-100 my-3" %>
         </div>
         <div id="map"
            style="width: 100%; height: 150px; border-radius: 15px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
    <% end %>
    </div>
    <%= render 'shared/new_message_button'%>
</div>
<!-- btn-main -->
<!-- btn-main -->

app/views/messages/show.html.erb
<h4> <%= @message.content %> </h4>
<%= cl_image_tag @message.photo.key %>


<li class="list-group-item">
      <%= @message.content %>
      <%= link_to "Remove",
                  message_path(@message),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
</li>

<div class="map-container pr-3">
    <div id="map"
        style="width: 600px; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="w-100 text-center">
    <h1><strong>OurSpot</strong></h1>
    <p>Make our mark</p>
    <div class="mt-4 log-in">
      <% if current_user %>
        <%= link_to "See my spots", chatrooms_path, class: "btn btn-main rounded-pill btn-log-in w-40 py-2 px-3"  %>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-main rounded-pill w-50 btn-log-in mb-3" %>
        <div class="sign-up w-100">
          <span class="white">New to OurSpot?</span> <%= link_to new_user_registration_path, class: "white"  do%>
            <span class="white" style="text-decoration: underline;">Sign Up</span>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= render 'shared/new_message_button' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <i class="fas fa-user-plus" style="margin-right: 5px;"></i>
  <i class="fas fa-user-cog"></i>
  <% end %>
  <%=  link_to root_path do %>
    <%= image_tag "ourspot-pos.png", width: "110" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new_message_button.html.erb
<div class="footer-container transparent">
    <%= link_to (image_tag "home-icon.svg", class:"icon-footer"), root_path %>
    <%= link_to (image_tag "chatrooms-icon.svg", class:"icon-footer"), chatrooms_path %>
    <%= link_to (image_tag "new-spot-icon.svg", class:"logo-footer", id:"message-btn"), new_message_path %>
    <%= link_to (image_tag "friends-icon.svg", class:"icon-footer"), users_path %>
    <% if current_user %>
    <%= link_to (image_tag "user-icon.svg", class:"icon-footer"), profile_path(current_user) %>
    <% end %>
</div>

app/views/shared/the navbar.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <i class="fas fa-user-plus" style="margin-right: 5px;"></i>
  <i class="fas fa-user-cog"></i>
  <% end %>
  <%=  link_to root_path do %>
    <%= image_tag "ourspot-pos.png", width: "110" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="background">
  <div class="header header-index d-flex">
    <div class="img-icon-separate">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-sm" %>
      <% else %>
        <img class="avatar-sm" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="">
      <% end %>
      <i class="fas fa-search white icon-search"></i>
    </div>
    <h4 style="color: lightgoldenrodyellow;" class="mt-3 caps-title">Find Friends</h4>
  </div>
  <div class="chat-container chat-background pt-2">
      <div class="friend-wrap">
        <% if current_user.requested_friends.empty? %>
          <p class="text-left" style= "color:lightgoldenrodyellow">Nothing yet, time to add some friends!</p>
        <% else %>
          <% current_user.requested_friends.each do |friend| %>
            <div class="d-flex friend-request">
              <% if friend.photo.attached? %>
                <%= cl_image_tag friend.photo.key, class: "avatar-sm" %>
              <% else %>
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="" class="avatar-sm">
              <% end %>
              <!-- <img src="https://images.unsplash.com/photo-1582214448344-4cb7e35711f7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80" alt="" class="avatar"> -->
              <span class="ml-3 text-big"><%= friend.username %></span class="ml-3">
              <div class="d-flex friend-icons">
<!--                 <i class="fas fa-check mr-3 accept"><%# current_user.accept_request(friend) %></i>
                <i class="fas fa-times reject"><%# current_user.decline_request(friend) %></i> -->
                <%= link_to "Accept", accept_path(user_id: friend.id), method: :put, class:"btn btn-main-dark btn-primary" %>
                
                <%= link_to "Reject", reject_path(user_id: friend.id), method: :put, class:"btn btn-main-dark btn-primary" %>
            
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
     <ul class="list-unstyled">
        <% @users.each do |user| %>
          <li class="chat-card" style="padding: 0 !important;">
            <div class="d-flex profile-box p-3">
              <div class="profile-details">
                <% if user.photo.attached? %>
                  <%= cl_image_tag user.photo.key, class: "avatar-sm" %>
                <% else %>
                    <img class="avatar-sm" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="">
                <% end %>
                <p class="ml-3 bold-large-text" style="color: black !important"><%= user.username %></p>
              </div>
              <% if current_user.pending_friends.include?(user) %>
                <div>
                  <%= link_to "Pending", add_friend_path(user_id: user.id), method: :put, class:"btn btn-main-dark btn-primary disabled" %>
                </div>
              <% else %>
                <div>
                  <%= link_to "Add friend", add_friend_path(user_id: user.id), method: :put, class:"btn btn-main-dark btn-primary" %>
                </div>
              <% end %>
            </div>
          </li>
      <!-- <div class="underline"></div> -->
        <% end %>
      </ul>

    </div>
    <%= render 'shared/new_message_button' %>
</div>

app/views/users/show_profile.html.erb
<div class="background">
  <div class="profile-container">
    <div class="profile-header">
      <div class="log-out-btn">
        <%= link_to destroy_user_session_path, method: :delete, class:"yellow-text"  do%>
          <p class="white-text my-2 caps-title">Log out</p>
        <% end %>
      </div>
    </div>
    <div class="section profile-content">
      <div class="profile-content-container">
        <div class="owner">
          <div class="owner-avatar">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, class: "img-circle img-align"%>
            <% else %>
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToplStyx8pu0DsUkR-zSI6hAAN-vzcrZF0HA&usqp=CAU" alt="" class="img-circle img-align">
            <% end %>
          </div>
          <div class="name">
            <h4 class="title"><%= current_user.username %></h4>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/new_message_button' %>
</div>